# **Numpy Array**

In [1]:
!pip install -q tensorflow==2.1.0

     |████████████████████████████████| 421.8MB 38kB/s 
     |████████████████████████████████| 3.9MB 34.9MB/s 
     |████████████████████████████████| 450kB 30.9MB/s 


In [0]:
import numpy as np

In [0]:
mylist = [1,2,3]

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
type(mylist)

list

In [0]:
nested_list = [[1,2], [3,4], [5,6]]

In [7]:
nested_list

[[1, 2], [3, 4], [5, 6]]

In [8]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

##**np.arange()** 
Function to create numpy array starting and stop and distance in between

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# to get even numbers. np.arange() generates integers. most other np functions generate floating point precission 
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
# to generate array of zeros. it generates floating point precission zeros.
np.zeros(3)

array([0., 0., 0.])

In [12]:
# to generate array of zeros with dimensions. 0 index of tuple is for rows and 1 index is for columns. 
# if you want numbers to be integers, you can use second "dtype" argument to change to integers
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((4,10), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [16]:
# linear space function returns number elements you want in linear space.
# it is different than np.arange() in fashion that it finds number itself. 
# you have to mention counts of the numbers that you want. 
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [17]:
# linear space function returns number elements you want in linear space.
# it is different than np.arange() in fashion that it finds number itself. 
# you have to mention counts of the numbers that you want. 
# This time 21 points between 0 and 10
# linspace does include stopping point
# in this case, 10 is included
np.linspace(0, 10, 21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [18]:
# eye() creates identity matrix like in linear algebra
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
# np.random object has many random functions
# if you want to know, hit shift+tab after np.random.
# each function gives different kind of random distribution
# if you want to know particular function, like np.random.rand,
# just simply press shift+tab
# default is between 0 and 1
np.random.rand(2)

array([0.43141592, 0.83822491])

In [20]:
# if you need matrix in random, you just use 2 numbers.
# no tuple. 
np.random.rand(3,4)

array([[0.85866212, 0.21692862, 0.25860923, 0.32372062],
       [0.20312863, 0.68931443, 0.36188778, 0.62763834],
       [0.13751355, 0.57962105, 0.27200874, 0.86750545]])

In [21]:
# for standard normal distribution
# means, mean = 0 and standard deviation =1
# since it is 1, variance is also 1
# therefore, it allows us to have some negative numbers too
np.random.randn(5,5)

array([[ 1.86928126,  0.45920866, -0.16463516, -1.65681249, -1.39236213],
       [-0.59405267, -0.86045681, -0.166256  ,  2.03813111, -1.38977289],
       [-1.10218647, -0.78870255,  1.20924617, -0.3626343 , -0.75388795],
       [ 0.24683471, -0.02843029,  0.80629109,  0.98686313,  0.34172354],
       [-0.56419773,  0.84650228, -0.56542691, -0.63613701, -0.79054391]])

In [22]:
# random integers pick integer from low to high-1
# for example, you want to pick up the random age of a person
np.random.randint(1,100)

28

In [23]:
# if you want 10 random ages of people
np.random.randint(1,100, 10)

array([42, 81, 12, 16, 35, 14, 66, 65, 31, 35])

In [24]:
# if you want certain random ages of people in matrix,
# you enter tuple of dimension
np.random.randint(1,100, (3, 4))

array([[19, 32,  8, 79],
       [88, 70, 17, 27],
       [56, 16,  9, 50]])

In [25]:
# if you want same numbers for you and others,
# or all the time, you chose seed with arbitrary number
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [26]:
# from now for few cells, you will learn to reshape your arrays
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0, 50, 10)
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [28]:
arr.shape

(25,)

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [31]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
# you cannot reshape the array in dimensions that can't make sense
# arr has 25 elments. if you try to reshape into 3x6 matrix,
# it will not be able to. It is because; 3x6 are 18 elements. Not 25!
arr.reshape(3,6)


ValueError: ignored

In [33]:
# if you want to know max value in array
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [34]:
ranarr.max()

39

In [35]:
# if you want to know the index location of max
ranarr.argmax()

7

In [36]:
# if you want to know the minimum
ranarr.min()

2

In [37]:
# if you want to know the index of minimum
ranarr.argmin()

9

In [38]:
# if you want to know the data type
ranarr.dtype

dtype('int64')

In [0]:
myarr = np.random.rand(4)

In [41]:
myarr.dtype

dtype('float64')