In [1]:
!pip install -q tensorflow==2.1.0

     |████████████████████████████████| 421.8MB 38kB/s 
     |████████████████████████████████| 3.9MB 37.2MB/s 
     |████████████████████████████████| 450kB 45.0MB/s 


# **Numpy Operations**

In [0]:
import numpy as np

In [0]:
arr = np.arange(0, 10)

In [0]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [0]:
# take original and add to it. if you do this operation, these
# arrays have to be same size
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [0]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [0]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [0]:
# element divided by zero will give warning and nan value at divided by zero
arr / arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [0]:
1 / 0

ZeroDivisionError: ignored

In [0]:
# if scalar divided by 0, then it will give infinity at that point
1 / arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [0]:
# numpy comes with many function
# numpy for squareroot of every number
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [0]:
# numpy trigonometric function
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [0]:
# numpy log function
# when trying to divide by 0, numpy give warning. 
# not full error
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

[Universal functions (ufunc)](https://docs.scipy.org/doc/numpy/reference/ufuncs.html)

In [0]:
# numpy has many summary statistics functions
# np.sum() sums up all the elments
print(arr)
print(arr.sum())

[0 1 2 3 4 5 6 7 8 9]
45


In [0]:
# mean is mean()
# maximum element can be found max()
# min() for minimum
print(arr.mean())
print(arr.max())
print(arr.min())

4.5
9
0


In [0]:
# variance and standard deviation
print(arr.var())
print(arr.std())

8.25
2.8722813232690143


In [0]:
np.arange(0, 25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [0]:
arr2d = np.arange(0, 25).reshape(5,5)
arr2d.shape

(5, 5)

In [0]:
# sums all numbers in all rows
arr2d.sum()

300

In [0]:
# you can get sum accross columns or rows
# for sum accros columns
# axis=0 means, perform operation accross the rows.
# which gives us technically sum of columns
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [0]:
# axis = 1 means, perform operations accros index 1
# Python starts from 0
# axis = 1 meansm, peform accross columns
# technically adding up each row.
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

# **Numpy Test**

In [0]:
import numpy as np

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [6]:
np.arange(10, 51, dtype=int)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [36]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [7]:
np.arange(0, 9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.rand(1)

array([0.44022548])

In [37]:
np.arange(0, 1, .01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

In [39]:
arr1 = np.arange(1, 101) / 100
arr1.reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [11]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [14]:
np.random.standard_normal(25)

array([-1.18684723,  1.16192426, -0.53943878,  1.00368659, -1.46200951,
       -1.35448402,  1.10353109,  0.04138046,  0.71277464,  1.1463462 ,
       -1.4459654 ,  0.73876   , -1.17442882,  0.76452803,  2.2184826 ,
       -1.85509371,  0.65490712, -0.34668676, -0.28896336, -0.97244804,
       -0.67989068,  0.78678824, -0.53870377,  2.03522785, -1.86136161])

In [0]:
mat = np.arange(1,26).reshape(5,5)

In [16]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [0]:
slice1 = np.arange(12, 27, dtype=int).reshape(3, 5)

In [23]:
slice1

array([[12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26]])

In [25]:
slice1[:, :-1]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [41]:
mat[3,4]

20

In [28]:
np.array([2, 7, 12]).reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [43]:
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [29]:
np.arange(21, 26, dtype=int)

array([21, 22, 23, 24, 25])

In [30]:
np.arange(16, 26, dtype=int).reshape(2, 5)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [31]:
mat.sum()

325

In [32]:
mat.std()

7.211102550927978

In [34]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])