In [1]:
!pip install -q tensorflow==2.1.0

     |████████████████████████████████| 421.8MB 39kB/s 
     |████████████████████████████████| 450kB 44.2MB/s 
     |████████████████████████████████| 3.9MB 24.2MB/s 


# **Numpy Operations**

In [0]:
import numpy as np

In [0]:
arr = np.arange(0, 10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [7]:
# take original and add to it. if you do this operation, these
# arrays have to be same size
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
# element divided by zero will give warning and nan value at divided by zero
arr / arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
1 / 0

ZeroDivisionError: ignored

In [12]:
# if scalar divided by 0, then it will give infinity at that point
1 / arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [13]:
# numpy comes with many function
# numpy for squareroot of every number
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [14]:
# numpy trigonometric function
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [15]:
# numpy log function
# when trying to divide by 0, numpy give warning. 
# not full error
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

[Universal functions (ufunc)](https://docs.scipy.org/doc/numpy/reference/ufuncs.html)

In [16]:
# numpy has many summary statistics functions
# np.sum() sums up all the elments
print(arr)
print(arr.sum())

[0 1 2 3 4 5 6 7 8 9]
45


In [17]:
# mean is mean()
# maximum element can be found max()
# min() for minimum
print(arr.mean())
print(arr.max())
print(arr.min())

4.5
9
0


In [18]:
# variance and standard deviation
print(arr.var())
print(arr.std())

8.25
2.8722813232690143


In [19]:
np.arange(0, 25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
arr2d = np.arange(0, 25).reshape(5,5)
arr2d.shape

(5, 5)

In [21]:
# sums all numbers in all rows
arr2d.sum()

300

In [22]:
# you can get sum accross columns or rows
# for sum accros columns
# axis=0 means, perform operation accross the rows.
# which gives us technically sum of columns
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [23]:
# axis = 1 means, perform operations accros index 1
# Python starts from 0
# axis = 1 meansm, peform accross columns
# technically adding up each row.
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])