In [1]:
!pip install -q tensorflow==2.1.0

     |████████████████████████████████| 421.8MB 36kB/s 
     |████████████████████████████████| 450kB 40.6MB/s 
     |████████████████████████████████| 3.9MB 49.6MB/s 


In [0]:
import numpy as np

In [0]:
arr = np.arange(0,11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr[8]

8

In [13]:
arr[1:5]

array([1, 2, 3, 4])

In [14]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [15]:
arr[:5]

array([0, 1, 2, 3, 4])

In [16]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr[0:5] = 100

In [19]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [0]:
arr = np.arange(0, 11)

In [0]:
slice_of_arr = arr[0:5]

In [22]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
slice_of_arr[:] = 99

In [26]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [27]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [0]:
arr_copy = arr.copy()

In [29]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [0]:
arr_copy[:] = 100

In [31]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [32]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [0]:
# 2D Array
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [34]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [35]:
# if you want to grab a row through indexing
print(arr_2d[0])
print(arr_2d[2])

[ 5 10 15]
[35 40 45]


In [36]:
# if you want to get 25
# first way
print(arr_2d[1, 1])

# second way
print(arr_2d[1][1])

25
25


In [37]:
# slicing method
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [0]:
arr = np.arange(0, 11)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
# conditional statement boolean values. either True or False
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [0]:
# now, you can assign this bolean array to a variable
bool_arr = arr > 4

In [42]:
# now, you can use this boolean array as a condition to select from your actual array
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [43]:
# we can do this in one step
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])